on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write # for creating labels
  pull-requests: write
  actions: write # for triggering the pr-opened workflow?
  checks: write # for triggering the pr-opened workflow?

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
